######################################################################
#
# File name : AXI_master_and_slave_bd_wrapper_simulate.do
# Created on: Tue Apr 01 23:55:22 PDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
# vsim -c -lib xil_defaultlib testbench_opt
vsim -lib xil_defaultlib testbench_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {AXI_master_and_slave_bd_wrapper_wave.do}

view wave
view structure
view signals

#do {AXI_master_and_slave_bd_wrapper.udo}
do {wave.do}

log -r /*

run 1000ns

#quit -force
