######################################################################
#
# File name : AXI_master_and_slave_bd_wrapper_elaborate.do
# Created on: Tue Apr 01 23:55:22 PDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 \
	+acc=npr \
	-suppress 10016 \
	-L unisims_ver \
	-L unimacro_ver \
	-L secureip \
	-L xpm \
	-L axi_vip_v1_1_19 \
	-L clk_vip_v1_0_5 \
	-L axi_infrastructure_v1_1_0 \
	-L rst_vip_v1_0_7 \
	-L xilinx_vip \
	-L xil_defaultlib \
	-work xil_defaultlib \
	xil_defaultlib.glbl \
	xil_defaultlib.testbench \
	-o testbench_opt

# 	xil_defaultlib.AXI_master_and_slave_bd_wrapper \
# 	-o AXI_master_and_slave_bd_wrapper_opt
