######################################################################
#
# File name : AXI_master_and_slave_bd_wrapper_wave.do
# Created on: Tue Apr 01 23:55:22 PDT 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
# if { [catch {[add wave *]}] } {}
# add wave /glbl/GSR
