#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Tue Apr 01 23:55:22 PDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************

bin_path="/eda/siemens/Questa/2025.1/questasim/linux_x86_64"
set -Eeuo pipefail
rm -rf questa_lib
mkdir -p questa_lib
source compile_DUT.do 2>&1 | tee compile.log
testbench_compile.sh 2>&1 | tee testbench_compile.log
