#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Siemens Questa Advanced Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Apr 01 23:55:22 PDT 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
vsim -64 -c -do "do {AXI_master_and_slave_bd_wrapper_simulate.do}" -l simulate.log

